services:
  postgres:
    container_name: postgres
    image: postgres:13
    environment:
      POSTGRES_DB: metastore
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
    ports:
      - "5432:5432"
    volumes:
      - ./pg-data:/var/lib/postgresql/data

  hive-metastore:
    container_name: hive-metastore
    image: apache/hive:3.1.3
    platform: linux/amd64
    environment:
      - SERVICE_NAME=metastore
      - DB_TYPE=postgres
      - HIVE_METASTORE_DB_TYPE=postgres
      - HIVE_METASTORE_DB_HOST=postgres
    ports:
      - "9083:9083"
    depends_on:
      - postgres

  runner:
    container_name: runner
    build:
      context: .
      dockerfile: runner.Dockerfile
    volumes:
      - ./examples:/app/examples
      #- ./pyiceberg.yaml:/root/.pyiceberg/config.yaml:ro
      - ./tests/test_integration.py:/app/tests/test_integration.py
    depends_on:
      - postgres
      - hive-metastore
    environment:
      PYICEBERG_CATALOG__HIVE__TYPE: hive
      PYICEBERG_CATALOG__HIVE__URI: thrift://hive-metastore:9083
      PYICEBERG_CATALOG__HIVE__WAREHOUSE: file:///warehouse/
      PYICEBERG_WAREHOUSE: file:///warehouse/
    command: ["tail", "-f", "/dev/null"]
